### ISSUE TITLE
Add a quick open for libraries

### ISSUE THREAD

**Issue by triplejam** [jdkr/textadept-dev-tools#1]
This is pretty useful. I think a quick open function for library files would be helpful too.

**Comment by triplejam** [comment]
I think there are two ways do it. The first would be to search through each library with their individual filters and combine the results into one list. The second would be first being prompted for which library you want to search through and then just searching through that one. I have already implemented the first. I will make a pull request if that way sounds good.

**Comment by jdkr** [comment]
Hello James,
I am glad that you want to do this extension by yourself. Both ways should be ok. Maybe with the first way there will be (depending on the amount of files in the libraries) many entries in the dialog. But since there is a Quick Search it should be ok. 
If you've tested your implementation you can do a pull request. I'm still struggling with the git-commands ;-)

**Comment by jdkr** [comment]
And there should be:
- a keybinding : keys['ad']['q']['o']['l']
- an entry in the menu (the part that shows up when a project is loaded)
- a documentation in the readme.md. (I've converted the readme.md into readme.html with pandoc)

**Comment by jdkr** [comment]
I have thought also a little how to implement this. Maybe the second way by first choosing a library is better, because of two things:
- There is already the textadept built-in function: io.quick_open(path, filter), so we should use this. So first choose a library-path from a dialog, and then take its filter from the table with with the libraries. After this transfer them both to the built-in function.
- I've seen that the limit of entries in the quick-open dialog io.quick_open_max is set to 1000. Therefore it would be less possible to reach this limit when opening single libraries.

I think also we should avoid to duplicate textadept's code into this module. So maybe you could try to implement the other way (should be even easier), or I will do this sometime later.

For your info how to use pandoc:
pandoc README.md -o README.html

Cheers,
Johannes

**Comment by triplejam** [comment]
Ok. I will do it sometime.
